### ISSUE TITLE
The dataset for audio data was not provided

### ISSUE THREAD

**Issue by Aakash-shetty** [Bikashgrg/Environmental-sound-classification-for-crime-detection#1]
`# Complete Dataset file path
dataset_path = './audio'`
`audiopath = './audio/fold1/7061-6-0-0.wav'`
./audio folder was not present in the project file
![ss1](https://github.com/Bikashgrg/Environmental-sound-classification-for-crime-detection/assets/102685620/96dfcc29-8258-463e-b2b9-01ab694c0c16)
![ss2](https://github.com/Bikashgrg/Environmental-sound-classification-for-crime-detection/assets/102685620/d5ee40d8-41c6-4939-9ca2-017df7de4197)

**Comment by Bikashgrg** [comment]
Hi Aakash,
The audio dataset for this project was really big due to which I did not put it in the github. However, it is an publically available data so you can easily get it. The link for this audio dataset is (https://urbansounddataset.weebly.com/urbansound8k.html) which I've also mentioned in the Readme section of the repository.
Thank you and enjoy
